INSERT INTO TB_CATEGORIA (NOME_CATEGORIA) VALUES ('Notebook');
INSERT INTO TB_CATEGORIA (NOME_CATEGORIA) VALUES ('Smartphone');
INSERT INTO TB_CATEGORIA (NOME_CATEGORIA) VALUES ('TV');
INSERT INTO TB_CATEGORIA (NOME_CATEGORIA) VALUES ('Tablet');

INSERT INTO TB_MARCA (NOME_MARCA) VALUES ('LG');
INSERT INTO TB_MARCA (NOME_MARCA) VALUES ('Apple');
INSERT INTO TB_MARCA (NOME_MARCA) VALUES ('Samsumg');
INSERT INTO TB_MARCA (NOME_MARCA) VALUES ('Sony');


INSERT INTO TB_PRODUTO (NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, ID_CATEGORIA, ID_MARCA) VALUES ('Nome do produto 1', 'sku-0001', 'Descrição do Produto 1', 'Características do produto 1', 1.99, 1, 1);
INSERT INTO TB_PRODUTO (NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, ID_CATEGORIA, ID_MARCA) VALUES ('Nome do produto 2', 'sku-0002', 'Descrição do Produto 2', 'Características do produto 2', 2.99, 2, 2);
INSERT INTO TB_PRODUTO (NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, ID_CATEGORIA, ID_MARCA) VALUES ('Nome do produto 3', 'sku-0002', 'Descrição do Produto 3', 'Características do produto 3', 3.99, 3, 3);
INSERT INTO TB_PRODUTO (NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, ID_CATEGORIA, ID_MARCA) VALUES ('Nome do produto 4', 'sku-0002', 'Descrição do Produto 4', 'Características do produto 4', 4.99, 4, 4);


INSERT INTO TB_LOJA (NOME_LOJA) VALUES ('Americanas');
INSERT INTO TB_LOJA (NOME_LOJA) VALUES ('Fast Shop');
INSERT INTO TB_LOJA (NOME_LOJA) VALUES ('Magazine Luiza');
INSERT INTO TB_LOJA (NOME_LOJA) VALUES ('Submarino');

INSERT INTO TB_PRODUTO_LOJA (ID, ID_LOJA) VALUES (1, 1);
INSERT INTO TB_PRODUTO_LOJA (ID, ID_LOJA) VALUES (1, 3);
INSERT INTO TB_PRODUTO_LOJA (ID, ID_LOJA) VALUES (2, 1);
INSERT INTO TB_PRODUTO_LOJA (ID, ID_LOJA) VALUES (2, 4);
INSERT INTO TB_PRODUTO_LOJA (ID, ID_LOJA) VALUES (3, 2);
INSERT INTO TB_PRODUTO_LOJA (ID, ID_LOJA) VALUES (4, 2);